### PR TITLE
#17 Fixed-width configuration update.

### PR DESCRIPTION
**Pull request by jhorcicka**
Solves #17 

Fixed-width configuration was updated. New elements for EBCDIC support. 

docs-update

### CODE REVIEW

**Comment by LosD** [comment]
LGTM!

**Comment by LosD** [comment]
By the way, it's "fixes", not "solves" for Github to pick it up. I'll close the issue :)

**Comment by jhorcicka** [comment]
I did not know "Fixes" is a keyword. I used "fixes" for bugs and "solves" for enhancements. :-)

**Comment by LosD** [comment]
Oh!
If you use "fixes" it will automatically close the linked issue, so you should use that always (or another of the keywords that [closes it](https://help.github.com/articles/closing-issues-via-commit-messages/)) :)

**Comment by jhorcicka** [comment]
Ha! I can use "resolves" instead of "solves". :-)

**Comment by LosD** [comment]
:laughing:

**Pull request merged**
